### PR TITLE
Update licensing text

### PR DESCRIPTION
**Pull request by ghost**
Minor tweaks to licensing stuff.

Fixed cut off LICENSE file.

Adding license boilerplate to all source files.

### CODE REVIEW

**Comment by ghost** [comment]
@jjasghar here it is

**Comment by jjasghar** [comment]
@mattcousens it looks like it broke the compile?

```
Step 9/11 : RUN cd /src && cobc -free -x -o helloworld-exe helloworld.cobol

 ---> Running in 0dc4aad4597d

helloworld.cobol:5: Error: syntax error, unexpected OF, expecting TOKEN

The command '/bin/sh -c cd /src && cobc -free -x -o helloworld-exe helloworld.cobol' returned a non-zero code: 1

The command "docker build -t cobol_test ." failed and exited with 1 during .
```

Which is weird just adding the comments?

**Comment by ghost** [comment]
Trying this again using a *> for the comments

**Comment by jjasghar** [comment]
Awesome, thanks for this :)

**Pull request merged**
